runtime: python39

entrypoint: gunicorn -b :$PORT server:app

env_variables:
  AZURE_MYSQL_HOST: "<DATABASE_HOST>.mysql.database.azure.com"
  AZURE_MYSQL_PORT: "3306"
  AZURE_MYSQL_USER: "<DATABASE_USER>"
  AZURE_MYSQL_PASS: "<DATABASE_PASSWORD>"
  AZURE_MYSQL_DB:   "<DATABASE_NAME>"
  GEMINI_API_KEY: "<API_KEY>"

automatic_scaling:
  min_instances: 1
  max_instances: 1
  target_cpu_utilization: 0.65
